### ISSUE TITLE
Share the wallpaper

### ISSUE THREAD

**Issue by tylermadison** [juanmnl/hydra-theme#1]
Can you post up your wallpaper too? Really like the theme!

**Comment by juanmnl** [comment]
@tylermadison I'll try to find it. Erased all of them as i'm making my own now.
I'll post a link and ping you when i do. :smile:

**Comment by juanmnl** [comment]
@tylermadison  Found it! :) only 1920x1080 though. 
![1920x1080-red](https://cloud.githubusercontent.com/assets/699945/11007194/43a54bba-8496-11e5-866c-b5bdf1767956.jpg)
I made one [Reactjs](http://imgur.com/a/9VVtm) and a few [Nodejs](http://imgur.com/a/CciSf) wallpapers if you want to check 'em up.

:v:
